var Settings_8h =
[
    [ "Settings", "structSettings.html", "structSettings" ],
    [ "AeroModuleSettings", "structSettings_1_1AeroModuleSettings.html", "structSettings_1_1AeroModuleSettings" ],
    [ "AeroponicsSettings", "structSettings_1_1AeroponicsSettings.html", "structSettings_1_1AeroponicsSettings" ],
    [ "AeroponicsSettings_TankSpecific", "structSettings_1_1AeroponicsSettings__TankSpecific.html", "structSettings_1_1AeroponicsSettings__TankSpecific" ],
    [ "DHTSensorSettings", "structSettings_1_1DHTSensorSettings.html", "structSettings_1_1DHTSensorSettings" ],
    [ "FanSettings", "structSettings_1_1FanSettings.html", "structSettings_1_1FanSettings" ],
    [ "GrowModuleSettings", "structSettings_1_1GrowModuleSettings.html", "structSettings_1_1GrowModuleSettings" ],
    [ "HempyBucketSettings", "structSettings_1_1HempyBucketSettings.html", "structSettings_1_1HempyBucketSettings" ],
    [ "HempyModuleSettings", "structSettings_1_1HempyModuleSettings.html", "structSettings_1_1HempyModuleSettings" ],
    [ "LightSensorSettings", "structSettings_1_1LightSensorSettings.html", "structSettings_1_1LightSensorSettings" ],
    [ "LightsSettings", "structSettings_1_1LightsSettings.html", "structSettings_1_1LightsSettings" ],
    [ "ModuleSkeletonSettings", "structSettings_1_1ModuleSkeletonSettings.html", "structSettings_1_1ModuleSkeletonSettings" ],
    [ "PHSensorSettings", "structSettings_1_1PHSensorSettings.html", "structSettings_1_1PHSensorSettings" ],
    [ "PressureSensorSettings", "structSettings_1_1PressureSensorSettings.html", "structSettings_1_1PressureSensorSettings" ],
    [ "SoundSettings", "structSettings_1_1SoundSettings.html", "structSettings_1_1SoundSettings" ],
    [ "WaterLevelSensorSettings", "structSettings_1_1WaterLevelSensorSettings.html", "structSettings_1_1WaterLevelSensorSettings" ],
    [ "WaterPumpSettings", "structSettings_1_1WaterPumpSettings.html", "structSettings_1_1WaterPumpSettings" ],
    [ "WaterTempSensorSettings", "structSettings_1_1WaterTempSensorSettings.html", "structSettings_1_1WaterTempSensorSettings" ],
    [ "WeightSensorSettings", "structSettings_1_1WeightSensorSettings.html", "structSettings_1_1WeightSensorSettings" ],
    [ "loadSettings", "Settings_8h.html#ad971c9812747afb3057cd98892437c13", null ],
    [ "restoreDefaults", "Settings_8h.html#ac6ea025bbd7c07eb499581c99b13ed58", null ],
    [ "saveSettings", "Settings_8h.html#ac0ce9cbac65602e667e78fe16e0d51fe", null ],
    [ "CurrentTime", "Settings_8h.html#a197fc7fece7964f371e3331919d596bb", null ],
    [ "LongMessage", "Settings_8h.html#a29e392d833e97bf88f780e9fdf22373f", null ],
    [ "ShortMessage", "Settings_8h.html#a6084d34751a3c3b5585d06dc1c0dd9f6", null ]
];